[project]
name = "comments-classification-maksim-romanov"
version = "0.1.0"
description = "ML practice"
authors = ["Maksim Romanov <mxromv@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia", "anaconda"]
platforms = ["linux-64", "win-64"]
readme = "README.md"

[tasks]

[dependencies]
python = ">=3.11"
git = ">=2.42"
hydra-core = ">=1.3"
jupyter = ">=1.0"
matplotlib = ">=3.8"
more-itertools = ">=10.1"
numpy = ">=1.26"
omegaconf = ">=2.3"
plotly = ">=5.18"
polars = ">=0.19"
pyarrow = "13.0.*"
pydantic = ">=2.4"
quarto = ">=1.3"
s3fs = ">=2021.7"
scikit-learn = ">=1.3"
toolz = ">=0.12"
tqdm = ">=4.66"
ruff = ">=0.1"
commitizen = ">=2.28"
mypy = ">=1.6"
pre-commit = ">=3.5"
pytorch = "2.1.0.*"
pytorch-cuda = "11.8.*"
transformers = "4.35.2.*"
datasets = "2.14.7.*"
pymorphy3 = "1.2.0.*"
nltk = "3.8.1.*"
pandas = "2.1.3.*"
imbalanced-learn = "0.11.0.*"
