model:
  _target_: transformers.AutoModelForSequenceClassification.from_pretrained
  _convert_: object
  pretrained_model_name_or_path: ai-forever/ruRoberta-large
  problem_type: single_label_classification
  cache_dir: ${model.cache_dir}
  device_map: ${general.device}

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  _convert_: object
  pretrained_model_name_or_path: ${encoder.model.pretrained_model_name_or_path}
  cache_dir: ${model.cache_dir}
  device_map: ${general.device}

short_name: ruRoberta