Model:
  _target_: catboost.CatBoostClassifier
  _convert_: object
  loss_function: MultiClass
  depth: 7
  iterations: 1000
  learning_rate: 0.01
  early_stopping_rounds: 30
  verbose: False
  task_type: GPU
  random_seed: ${general.random_state}
  custom_loss: F1
