defaults:
  - _self_
  - encoder: rubert_tiny_2
  - training: training
  - loss: cross_entropy
  - peft: lora

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  input_path: ../data/practice_cleaned.csv
  interim_output: ../data/interim/${data.target}.csv
  column_use: data_patterns
  target: tag
  small_cats: ["Качество материалов", "Интерфейс платформы", "Общение с куратором"]
  max_length: 512

model:
  cache_dir: ../cache_dir
  output_dir: ../results
  checkpoints: ./checkpoints

fine_tuning:
  lora: False
  freeze: 0.0

general:
  device: cuda:0
  random_state: 42
  test_size: 0.3
